/**
 * users
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Company {
    /**
     * User ID
     */
    id?: string;
    /**
     * Full name
     */
    name?: string;
    /**
     * User\'s role (admin only)
     */
    description?: string;
    /**
     * User creation date
     */
    created?: string;
    /**
     * User email
     */
    last_update?: string;
}
