/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type ProjectTagsEnum = 'archived' | 'public' | 'default';

export const ProjectTagsEnum = {
    Archived: 'archived' as ProjectTagsEnum,
    Public: 'public' as ProjectTagsEnum,
    Default: 'default' as ProjectTagsEnum
}
