/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.12
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ProjectsGetHyperParametersRequest {
    /**
     * Project ID
     */
    project: string;
    /**
     * Page number
     */
    page?: number;
    /**
     * Page size
     */
    page_size?: number;
    include_subprojects?: boolean;
}
