/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ProjectsGetModelMetadataValuesRequest {
    /**
     * Project IDs
     */
    projects?: Array<string>;
    /**
     * Metadata key
     */
    key: string;
    /**
     * If set to \'true\' then collect values from both company and public models   otherwise company modeels only. The default is \'true\'
     */
    allow_public?: boolean;
    /**
     * If set to \'true\' and the project field is set then the result includes metadata   values from the subproject models
     */
    include_subprojects?: boolean;
}
