/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ProjectsMergeRequest {
    /**
     * Id of the project to merge
     */
    project?: string;
    /**
     * Id of the target project to merge to
     */
    target_project?: string;
}
