/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ProjectsGetHyperParametersResponse {
    /**
     * A list of hyper parameter names
     */
    parameters?: Array<string>;
    /**
     * Remaining results
     */
    remaining?: number;
    /**
     * Total number of results
     */
    total?: number;
}
