/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ProjectsDeleteResponse {
    /**
     * Number of projects deleted (0 or 1)
     */
    deleted?: number;
    /**
     * Number of tasks disassociated from the deleted project
     */
    disassociated_tasks?: number;
}
