/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ProjectsDeleteRequest {
    /**
     * Project id
     */
    project: string;
    /**
     * If not true, fails if project has tasks. If true, and project has tasks, they   will be unassigned
     */
    force?: boolean;
}
