/**
 * projects
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ProjectsGetTaskTagsResponse {
    /**
     * The list of unique tag values
     */
    tags?: Array<string>;
    /**
     * The list of unique system tag values. Returned only if \'include_system\' is set   to \'true\' in the request
     */
    system_tags?: Array<string>;
}
