/**
 * reports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OutputRoisEnum } from '././outputRoisEnum';
import { FilterRule } from '././filterRule';


export interface Filtering {
    /**
     * List of FilterRule (\'OR\' connection)
     */
    filtering_rules?: Array<FilterRule>;
    output_rois?: OutputRoisEnum;
}
