/**
 * reports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ReportsMoveRequest {
    /**
     * ID of the report to move
     */
    task: string;
    /**
     * Target project ID. If not provided, `project_name` must be provided.
     */
    project?: string;
    /**
     * Target project name. If provided and a project with this name does not exist, a   new project will be created. If not provided, `project` must be provided.
     */
    project_name?: string;
}
