/**
 * reports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ReportsCreateRequest {
    /**
     * Report name. Unique within the company.
     */
    name: string;
    /**
     * User-defined tags list
     */
    tags?: Array<string>;
    /**
     * Free text comment
     */
    comment?: string;
    /**
     * Report template
     */
    report?: string;
    /**
     * Project ID of the project to which this report is assigned Must exist[ab]
     */
    project?: string;
}
