/**
 * reports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ReportsShareRequest {
    /**
     * The ID of the report task to share/unshare
     */
    task: string;
    /**
     * If set to \'true\' then the report will be shared. Otherwise unshared.
     */
    share?: boolean;
}
