/**
 * reports
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ReportsUpdateRequest {
    /**
     * The ID of the report task to update
     */
    task: string;
    /**
     * Report name. Unique within the company.
     */
    name?: string;
    /**
     * User-defined tags list
     */
    tags?: Array<string>;
    /**
     * Free text comment
     */
    comment?: string;
    /**
     * Report template
     */
    report?: string;
}
