/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ServerInfoResponse {
    /**
     * Version string
     */
    version?: string;
    /**
     * Build number
     */
    build?: string;
    /**
     * VCS commit number
     */
    commit?: string;
    /**
     * Server UID
     */
    uid?: string;
    api_version?: string;
}
