/**
 * workers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ActivitySeries {
    /**
     * List of timestamps (in seconds from epoch) in the acceding order. The timestamps are separated by the requested interval.
     */
    dates?: Array<number>;
    /**
     * List of worker counts corresponding to the timestamps in the dates list. None values are returned for the dates with no workers.
     */
    counts?: Array<number>;
}
