/**
 * workers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface CurrentTaskEntry {
    /**
     * Worker ID
     */
    id?: string;
    /**
     * Worker name
     */
    name?: string;
    /**
     * Task running time
     */
    running_time?: number;
    /**
     * Last task iteration
     */
    last_iteration?: number;
}
