/**
 * workers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CurrentTaskEntry } from './currentTaskEntry';
import { IdNameEntry } from './idNameEntry';
import { QueueEntry } from './queueEntry';


export interface Worker {
    /**
     * Worker ID
     */
    id?: string;
    user?: IdNameEntry;
    company?: IdNameEntry;
    /**
     * IP of the worker
     */
    ip?: string;
    /**
     * Registration time
     */
    register_time?: Date;
    /**
     * Last activity time (even if an error occurred)
     */
    last_activity_time?: Date;
    /**
     * Last successful report time
     */
    last_report_time?: Date;
    task?: CurrentTaskEntry;
    queue?: QueueEntry;
    /**
     * List of queues on which the worker is listening
     */
    queues?: Array<QueueEntry>;
    /**
     * User tags for the worker
     */
    tags?: Array<string>;
}
