/**
 * workers
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface WorkersGetAllRequest {
    /**
     * Filter out workers not active for more than last_seen seconds. A value or 0 or   \'none\' will disable the filter.
     */
    last_seen?: number;
}
