/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ArtifactTypeData {
    /**
     * Description or textual data
     */
    preview?: string;
    /**
     * System defined raw data content type
     */
    content_type?: string;
    /**
     * Hash of raw data, without any headers or descriptive parts
     */
    data_hash?: string;
}
