/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type FilterByRoiEnum = 'disabled' | 'no_rois' | 'label_rules';

export const FilterByRoiEnum = {
    Disabled: 'disabled' as FilterByRoiEnum,
    NoRois: 'no_rois' as FilterByRoiEnum,
    LabelRules: 'label_rules' as FilterByRoiEnum
}
