/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface FilterLabelRule {
    /**
     * Lucene format query (see lucene query syntax). Default search field is label.keyword and default operator is AND, so searching for:  \'Bus Stop\' Blue  is equivalent to:  Label.keyword:\'Bus Stop\' AND label.keyword:\'Blue\'
     */
    label: string;
    /**
     * Range of times ROI appears in the frame (min, max). -1 for not applicable.             Both integers must be larger than or equal to -1.             2nd integer (max) must be either -1 or larger than or equal to the 1st integer (min)
     */
    count_range?: Array<number>;
    /**
     * Range of ROI confidence level in the frame (min, max). -1 for not applicable             Both min and max can be either -1 or positive.             2nd number (max) must be either -1 or larger than or equal to the 1st number (min)
     */
    conf_range?: Array<number>;
    /**
     * If set then the label must not exist or lucene query must not be true.             The default value is false
     */
    must_not?: boolean;
}
