/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Augmentation } from './augmentation';
import { Filtering } from './filtering';
import { Iteration } from './iteration';
import { Mapping } from './mapping';
import { View } from './view';


export interface Input {
    view?: View;
    frames_filter?: Filtering;
    mapping?: Mapping;
    augmentation?: Augmentation;
    iteration?: Iteration;
    /**
     * Key to DataView ID Mapping
     */
    dataviews?: { [key: string]: string; };
}
