/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface LabelSource {
    /**
     * List of source labels (AND connection). \'*\' indicates any label. Labels must exist in at least one of the dataset versions in the task\'s view
     */
    labels?: Array<string>;
    /**
     * Source dataset id. \'*\' for all datasets in view
     */
    dataset?: string;
    /**
     * Source dataset version id. Default is \'*\' (for all versions in dataset in the view) Version must belong to the selected dataset, and must be in the task\'s view[i]
     */
    version?: string;
}
