/**
 * tasks
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LastMetricsEvent } from './lastMetricsEvent';


/**
 * Last metric events, one for each variant hash
 */
export interface LastMetricsVariants {
    [key: string]: LastMetricsEvent;

}
