/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type ModelTypeEnum = 'input' | 'output';

export const ModelTypeEnum = {
    Input: 'input' as ModelTypeEnum,
    Output: 'output' as ModelTypeEnum
}
