/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type OutputRoisEnum = 'all_in_frame' | 'only_filtered' | 'frame_per_roi';

export const OutputRoisEnum = {
    AllInFrame: 'all_in_frame' as OutputRoisEnum,
    OnlyFiltered: 'only_filtered' as OutputRoisEnum,
    FramePerRoi: 'frame_per_roi' as OutputRoisEnum
}
