/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Output {
    /**
     * Storage id. This is where output files will be stored.
     */
    destination?: string;
    /**
     * Model id.
     */
    model?: string;
    /**
     * Task result. Values: \'success\', \'failure\'
     */
    result?: string;
    /**
     * Last error text
     */
    error?: string;
}
