/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Artifact } from './artifact';


export interface TasksAddOrUpdateArtifactsRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * Artifacts to add or update
     */
    artifacts: Array<Artifact>;
    /**
     * If set to True then both new and running task artifacts can be edited.   Otherwise only the new task ones. Default is False
     */
    force?: boolean;
}
