/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface TasksGetConfigurationNamesRequest {
    /**
     * Task IDs
     */
    tasks: Array<string>;
    /**
     * If set to \'true\' then the names for configurations with missing values are not   returned
     */
    skip_empty?: boolean;
}
