/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TasksDeleteModelsRequestModels } from '././tasksDeleteModelsRequestModels';


export interface TasksDeleteModelsRequest {
    /**
     * ID of the task
     */
    task: string;
    /**
     * The list of models to delete
     */
    models: Array<TasksDeleteModelsRequestModels>;
}
