/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TaskModelItem } from './taskModelItem';


export interface TaskModels {
    /**
     * The list of task input models
     */
    input?: Array<TaskModelItem>;
    /**
     * The list of task output models
     */
    output?: Array<TaskModelItem>;
}
