/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface TasksArchiveRequest {
    /**
     * List of task ids
     */
    tasks: Array<string>;
    /**
     * Reason for status change
     */
    status_reason?: string;
    /**
     * Extra information regarding status change
     */
    status_message?: string;
}
