/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface TasksGetOperationsLogRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * The amount of records to retrieve
     */
    page_size?: number;
    /**
     * The page to retrieve
     */
    page?: number;
    /**
     * The time sorting
     */
    order?: TasksGetOperationsLogRequest.OrderEnum;
}
export namespace TasksGetOperationsLogRequest {
    export type OrderEnum = 'asc' | 'desc';
    export const OrderEnum = {
        Asc: 'asc' as OrderEnum,
        Desc: 'desc' as OrderEnum
    }
}
