/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface TasksResetResponse {
    /**
     * List of deleted ES indices that were removed as part of the reset process
     */
    deleted_indices?: Array<string>;
    /**
     * Response from queues.remove_task
     */
    dequeued?: object;
    /**
     * Response from frames.rollback
     */
    frames?: object;
    /**
     * Response from events.delete_for_task
     */
    events?: object;
    /**
     * Number of output models deleted by the reset
     */
    deleted_models?: number;
    /**
     * Number of tasks updated (0 or 1)
     */
    updated?: number;
    /**
     * Updated fields names and values
     */
    fields?: object;
}
