/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ModelTypeEnum } from '././modelTypeEnum';


export interface TasksAddOrUpdateModelRequest {
    /**
     * ID of the task
     */
    task: string;
    /**
     * The task model name
     */
    name: string;
    /**
     * The model ID
     */
    model: string;
    type: ModelTypeEnum;
    /**
     * Iteration (used to update task statistics)
     */
    iteration?: number;
}
