/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Execution } from './execution';


export interface TasksCloneRequest {
    /**
     * ID of the task
     */
    task: string;
    /**
     * The name of the cloned task. If not provided then taken from the original task
     */
    new_task_name?: string;
    /**
     * The comment of the cloned task. If not provided then taken from the original   task
     */
    new_task_comment?: string;
    /**
     * The user-defined tags of the cloned task. If not provided then taken from the   original task
     */
    new_task_tags?: Array<string>;
    /**
     * The system tags of the cloned task. If not provided then empty
     */
    new_task_system_tags?: Array<string>;
    /**
     * The parent of the cloned task. If not provided then taken from the original   task
     */
    new_task_parent?: string;
    /**
     * The project of the cloned task. If not provided then taken from the original   task
     */
    new_task_project?: string;
    execution_overrides?: Execution;
}
