/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TaskUrls } from '././taskUrls';


export interface TasksResetResponse {
    /**
     * Number of tasks updated (0 or 1)
     */
    updated?: number;
    /**
     * Updated fields names and values
     */
    fields?: object;
    /**
     * Response from queues.remove_task
     */
    dequeued?: object;
    /**
     * Response from events.delete_for_task
     */
    events?: object;
    /**
     * Number of output models deleted by the reset
     */
    deleted_models?: number;
    urls?: TaskUrls;
}
