/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface TasksResetManyRequest {
    /**
     * IDs of the tasks to reset
     */
    ids: Array<string>;
    /**
     * If not true, call fails if the task status is \'completed\'
     */
    force?: boolean;
    /**
     * Clear script and execution sections completely
     */
    clear_all?: boolean;
    /**
     * If set to \'true\' then return the urls of the files that were uploaded by the   tasks. Default value is \'false\'
     */
    return_file_urls?: boolean;
    /**
     * If set to \'true\' then delete output models of the tasks that are not referenced   by other tasks. Default value is \'true\'
     */
    delete_output_models?: boolean;
}
