/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface TasksCompletedRequest {
    /**
     * If not true, call fails if the task status is not in_progress/stopped
     */
    force?: boolean;
    /**
     * Task ID
     */
    task: string;
    /**
     * Reason for status change
     */
    status_reason?: string;
    /**
     * Extra information regarding status change
     */
    status_message?: string;
}
