/**
 * tasks
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Task } from '././task';


export interface TasksGetAllExResponse {
    /**
     * List of tasks
     */
    tasks?: Array<Task>;
    /**
     * Scroll ID that can be used with the next calls to get_all_ex to retrieve more   data
     */
    scroll_id?: string;
}
