/**
 * serving
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.31
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContainerInstanceStatsReference } from '././containerInstanceStatsReference';


export interface ContainerInstanceStats {
    /**
     * Container ID
     */
    id?: string;
    /**
     * Uptime in seconds
     */
    uptime_sec?: number;
    /**
     * Number of requests
     */
    requests?: number;
    /**
     * Average requests per minute
     */
    requests_min?: number;
    /**
     * Average request latency in ms
     */
    latency_ms?: number;
    /**
     * The latest time when the container instance sent update
     */
    last_update?: string;
    /**
     * Array of reference items provided by the container instance. Can contain multiple reference items with the same type
     */
    reference?: Array<ContainerInstanceStatsReference>;
}
