/**
 * serving
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MachineStats } from '././machineStats';


export interface ServingContainerStatusReportRequest {
    /**
     * Container ID
     */
    container_id: string;
    /**
     * Endpoint name
     */
    endpoint_name: string;
    /**
     * Endpoint URL
     */
    endpoint_url?: string;
    /**
     * Model name
     */
    model_name: string;
    /**
     * Model source
     */
    model_source?: string;
    /**
     * Model version
     */
    model_version?: string;
    /**
     * Preprocess Artifact
     */
    preprocess_artifact?: string;
    /**
     * Input type
     */
    input_type?: string;
    /**
     * Input size in bytes
     */
    input_size?: number;
    /**
     * Uptime in seconds
     */
    uptime_sec?: number;
    /**
     * Number of requests
     */
    requests_num?: number;
    /**
     * Average requests per minute
     */
    requests_min?: number;
    /**
     * Average request latency in ms
     */
    latency_ms?: number;
    machine_stats?: MachineStats;
}
