/**
 * serving
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContainerInstanceStats } from '././containerInstanceStats';


export interface ServingGetEndpointDetailsResponse {
    /**
     * Endpoint name
     */
    endpoint?: string;
    /**
     * Model name
     */
    model?: string;
    /**
     * Model url
     */
    url?: string;
    /**
     * Model source
     */
    model_source?: string;
    /**
     * Model version
     */
    model_version?: string;
    /**
     * Preprocess Artifact
     */
    preprocess_artifact?: string;
    /**
     * Input type
     */
    input_type?: string;
    /**
     * Input size in bytes
     */
    input_size?: number;
    /**
     * Max of model instance uptime in seconds
     */
    uptime_sec?: number;
    /**
     * The latest time when one of the model instances was updated
     */
    last_update?: Date;
    instances?: Array<ContainerInstanceStats>;
}
