/**
 * serving
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ServingGetEndpointMetricsHistoryRequest {
  /**
   * Endpoint Url
   */
  endpoint_url: string;
  /**
   * Starting time (in seconds from epoch) for collecting statistics
   */
  from_date: number;
  /**
   * Ending time (in seconds from epoch) for collecting statistics
   */
  to_date: number;
  /**
   * Time interval in seconds for a single statistics point. The minimal value is 1
   */
  interval: number;
  /**
   * The type of the metrics to return on the chart
   */
  metric_type?: ServingGetEndpointMetricsHistoryRequest.MetricTypeEnum;
  /**
   * If set then return instance charts and total. Otherwise total only
   */
  instance_charts?: boolean;
}
export namespace ServingGetEndpointMetricsHistoryRequest {
  export type MetricTypeEnum = 'requests' | 'requests_min' | 'latency_ms' | 'cpu_count' | 'gpu_count' | 'cpu_util' | 'gpu_util' | 'ram_total' | 'ram_free' | 'gpu_ram_total' | 'gpu_ram_free' | 'network_rx' | 'network_tx';
  export const MetricTypeEnum = {
    Requests: 'requests' as MetricTypeEnum,
    RequestsMin: 'requests_min' as MetricTypeEnum,
    LatencyMs: 'latency_ms' as MetricTypeEnum,
    CpuCount: 'cpu_count' as MetricTypeEnum,
    GpuCount: 'gpu_count' as MetricTypeEnum,
    CpuUtil: 'cpu_util' as MetricTypeEnum,
    GpuUtil: 'gpu_util' as MetricTypeEnum,
    RamTotal: 'ram_total' as MetricTypeEnum,
    RamFree: 'ram_free' as MetricTypeEnum,
    GpuRamTotal: 'gpu_ram_total' as MetricTypeEnum,
    GpuRamFree: 'gpu_ram_free' as MetricTypeEnum,
    NetworkRx: 'network_rx' as MetricTypeEnum,
    NetworkTx: 'network_tx' as MetricTypeEnum
  }
}
