/**
 * serving
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.31
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ServingGetEndpointMetricsHistoryResponseInstancesValue {
    /**
     * The title of the series
     */
    title?: string;
    /**
     * List of timestamps (in seconds from epoch) in the acceding order. The timestamps are separated by the requested interval.
     */
    dates?: Array<number>;
    /**
     * List of values corresponding to the timestamps in the dates list.
     */
    values?: Array<number>;
}
