/**
 * login
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LoginSignupUserRequestSignupDataCrmFormData } from '././loginSignupUserRequestSignupDataCrmFormData';


/**
 * Info for the user sign up
 */
export interface LoginSignupUserRequestSignupData {
    /**
     * Sign-up token recieved from the sso_callback call. This field is required
     */
    signup_token?: string;
    /**
     * Company name for the user. This field is required. In case the user was invited to join the company this field cannot be changed
     */
    company_name?: string;
    /**
     * The user full name. This field is required
     */
    name?: string;
    /**
     * The user given name
     */
    given_name?: string;
    /**
     * The user family name
     */
    family_name?: string;
    /**
     * The user email
     */
    email?: string;
    /**
     * The user avatar
     */
    avatar?: string;
    crm_form_data?: LoginSignupUserRequestSignupDataCrmFormData;
    /**
     * The user additional info
     */
    additional_info?: object;
}
