/**
 * login
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Invite } from './invite';


export interface LoginGetSettingsResponse {
    /**
     * Auto-login domains
     */
    domains?: Array<string>;
    /**
     * Invite entries
     */
    invites?: Array<Invite>;
}
