/**
 * login
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WhitelistEntry } from '././whitelistEntry';


export interface LoginGetSettingsResponse {
    /**
     * Auto-login domains
     */
    domains?: Array<string>;
    /**
     * Whitelist entries
     */
    whitelist_entries?: Array<WhitelistEntry>;
}
