/**
 * login
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface LoginGetWhitelistRequest {
    /**
     * Email address. If provided, only whitelist entries which contain this email or   whose domain matches this email\'s domain will be returned NOTE: cannot be used   in conjunction with domain
     */
    email?: string;
    /**
     * Email domain. If provided, only whitelist entries with this specific domain   will be returned NOTE: cannot be used in conjunction with email
     */
    domain?: string;
}
