/**
 * login
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.13
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LoginWhiteListV15 } from '././loginWhiteListV15';


export interface LoginGetWhitelistResponse {
    /**
     * List of whitelist entries
     */
    entries?: Array<LoginWhiteListV15>;
}
