/**
 * queues
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface QueuesMoveTaskToFrontResponse {
    /**
     * The new position of the task entry in the queue (index, -1 represents bottom of   queue)
     */
    position?: number;
}
