/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface FieldMapping {
    /**
     * The source column name as specified in the only_fields
     */
    field: string;
    /**
     * The column name in the exported csv file
     */
    name?: string;
    /**
     * The column values mapping
     */
    values?: {key: any; value: any}[];
}
