/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Invite {
    /**
     * Invite id
     */
    id?: string;
    /**
     * Associated user id
     */
    user?: string;
    /**
     * Company ID
     */
    company?: string;
    /**
     * Invite creation time (UTC) 
     */
    created?: string;
    /**
     * Invite expiration time (UTC)
     */
    expires?: string;
}
