/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface OrganizationGetEntitiesCountResponse {
    /**
     * The number of projects matching the criteria
     */
    projects?: number;
    /**
     * The number of experiments matching the criteria
     */
    tasks?: number;
    /**
     * The number of models matching the criteria
     */
    models?: number;
    /**
     * The number of dataviews matching the criteria
     */
    dataviews?: number;
    /**
     * The number of pipelines matching the criteria
     */
    pipelines?: number;
    /**
     * The number of datasets matching the criteria
     */
    datasets?: number;
    /**
     * The number of reports matching the criteria
     */
    reports?: number;
}
