/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface OrganizationGetTagsRequest {
    /**
     * If set to \'true\' then the list of the system tags is also returned. The default   value is \'false\'
     */
    include_system?: boolean;
    filter?: object;
}
