/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface OrganizationGetInvitesRequest {
    /**
     * If True then only active invites returned. Default is True
     */
    active?: boolean;
    /**
     * List of IDs to filter by
     */
    id?: Array<string>;
    /**
     * List of user IDs used to filter results by the invite\'s creating user
     */
    user?: Array<string>;
    /**
     * Page number, returns a specific page out of the resulting list of tasks
     */
    page?: number;
    /**
     * Page size, specifies the number of results returned in each page (last page may   contain fewer results)
     */
    page_size?: number;
    /**
     * List of field names to order by. Use \'-\' prefix to specify descending order.   Optional, recommended when using page
     */
    order_by?: Array<string>;
}
