/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrganizationGetUserCompaniesResponseOwners } from '././organizationGetUserCompaniesResponseOwners';


export interface OrganizationGetUserCompaniesResponseCompanies {
    /**
     * Company ID
     */
    id?: string;
    /**
     * Company name
     */
    name?: string;
    /**
     * Number of users allowed in company
     */
    allowed?: number;
    /**
     * Number of users allocated for company
     */
    allocated?: number;
    /**
     * Company owners
     */
    owners?: Array<OrganizationGetUserCompaniesResponseOwners>;
}
