/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface OrganizationPrepareDownloadForGetAllResponse {
    /**
     * Prepare ID (use when calling \'download_for_get_all\')
     */
    prepare_id?: string;
}
