/**
 * organization
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FieldMapping } from '././fieldMapping';


export interface OrganizationPrepareDownloadForGetAllRequest {
    /**
     * List of task field names (nesting is supported using \'.\', e.g.   execution.model_labels). If provided, this list defines the query\'s projection   (only these fields will be returned for each result entry)
     */
    only_fields: Array<string>;
    /**
     * Download type. Determines the downloaded file\'s formatting and mime type.
     */
    download_type?: OrganizationPrepareDownloadForGetAllRequest.DownloadTypeEnum;
    /**
     * Allow public entities to be returned in the results
     */
    allow_public?: boolean;
    /**
     * If set to \'true\' then hidden entities are included in the search results
     */
    search_hidden?: boolean;
    /**
     * The type of the entity to retrieve
     */
    entity_type: OrganizationPrepareDownloadForGetAllRequest.EntityTypeEnum;
    /**
     * The name and value mappings for the exported fields. The fields that are not in   the mappings will not be exported
     */
    field_mappings?: Array<FieldMapping>;
}
export namespace OrganizationPrepareDownloadForGetAllRequest {
    export type DownloadTypeEnum = 'csv';
    export const DownloadTypeEnum = {
        Csv: 'csv' as DownloadTypeEnum
    }
    export type EntityTypeEnum = 'task' | 'model';
    export const EntityTypeEnum = {
        Task: 'task' as EntityTypeEnum,
        Model: 'model' as EntityTypeEnum
    }
}
