export const pipelineDummyConfiguration = {
  '0-0': {
    'base_task_id': 'sdfsfsdfsd',
    'queue': null,
    'parents': [],
    'stage': 'a',
    'timeout': null,
    'parameters': {'kwargs/name': '0-0', 'kwargs/reports': 0},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': 'running',
    'clone_task': false,
    'job_type': null,
    'job_started': new Date('2024-07-31T10:32:53.282000+00:00'),
    'job_ended': new Date('2024-07-31T10:33:48.329000+00:00'),
    'job_code_section': '0-0',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '1-0': {
    'base_task_id': null,
    'queue': null,
    'parents': ['0-0'],
    'stage': 'b',
    'timeout': null,
    'parameters': {'kwargs/name': '1-0', 'kwargs/reports': 0},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': 'completed',
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '1-0',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '1-1': {
    'base_task_id': null,
    'queue': null,
    'parents': ['0-0'],
    'stage': 'c', 'timeout': null,
    'parameters': {'kwargs/name': '1-1', 'kwargs/reports': 1},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '1-1',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '2-0': {
    'base_task_id': null,
    'queue': null,
    'parents': ['1-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '2-0', 'kwargs/reports': 0},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': 'pending',
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '2-0',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '2-1': {
    'base_task_id': null,
    'queue': null,
    'parents': ['1-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '2-1', 'kwargs/reports': 1},
    'configurations': {},
    'task_overrides': {},
    'executed': true,
    'status': 'running',
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '2-1',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '2-2': {
    'base_task_id': null,
    'queue': null,
    'parents': ['1-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '2-2', 'kwargs/reports': 4},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '2-2',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '2-3': {
    'base_task_id': null,
    'queue': null,
    'parents': ['1-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '2-3', 'kwargs/reports': 9},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '2-3',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-0': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-0', 'kwargs/reports': 0},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-0',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-1': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-1', 'kwargs/reports': 1},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-1',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-2': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-2', 'kwargs/reports': 4},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-2',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-3': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-3', 'kwargs/reports': 9},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-3',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-4': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-2'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-4', 'kwargs/reports': 16},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-4',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-5': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-2'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-5', 'kwargs/reports': 25},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-5',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-6': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-3'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-6', 'kwargs/reports': 36},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-6',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '3-7': {
    'base_task_id': null,
    'queue': null,
    'parents': ['2-3'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '3-7', 'kwargs/reports': 49},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '3-7',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-0': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-0', 'kwargs/reports': 0},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-0',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-1': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-1', 'kwargs/reports': 1},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-1',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-2': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-2', 'kwargs/reports': 4},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-2',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-3': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-3', 'kwargs/reports': 9},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-3',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-4': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-2'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-4', 'kwargs/reports': 16},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-4',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-5': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-2'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-5', 'kwargs/reports': 25},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-5',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-6': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-3'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-6', 'kwargs/reports': 36},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-6',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-7': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-3'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-7', 'kwargs/reports': 49},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-7',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-8': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-4'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-8', 'kwargs/reports': 64},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-8',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-9': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-4'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-9', 'kwargs/reports': 81},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-9',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-10': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-5'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-10', 'kwargs/reports': 100},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-10',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-11': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-5'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-11', 'kwargs/reports': 121},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-11',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-12': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-6'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-12', 'kwargs/reports': 144},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-12',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-13': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-6'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-13', 'kwargs/reports': 169},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-13',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-14': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-7'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-14', 'kwargs/reports': 196},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-14',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '4-15': {
    'base_task_id': null,
    'queue': null,
    'parents': ['3-7'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '4-15', 'kwargs/reports': 225},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '4-15',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-0': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-0', 'kwargs/reports': 0},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-0',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-1': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-0'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-1', 'kwargs/reports': 1},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-1',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-2': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-2', 'kwargs/reports': 4},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-2',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-3': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-1'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-3', 'kwargs/reports': 9},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-3',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-4': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-2'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-4', 'kwargs/reports': 16},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-4',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-5': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-2'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-5', 'kwargs/reports': 25},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-5',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-6': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-3'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-6', 'kwargs/reports': 36},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-6',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-7': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-3'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-7', 'kwargs/reports': 49},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-7',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-8': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-4'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-8', 'kwargs/reports': 64},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-8',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-9': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-4'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-9', 'kwargs/reports': 81},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-9',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-10': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-5'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-10', 'kwargs/reports': 100},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-10',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-11': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-5'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-11', 'kwargs/reports': 121},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-11',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-12': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-6'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-12', 'kwargs/reports': 144},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-12',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-13': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-6'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-13', 'kwargs/reports': 169},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-13',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-14': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-7'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-14', 'kwargs/reports': 196},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-14',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-15': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-7'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-15', 'kwargs/reports': 225},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-15',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-16': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-8'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-16', 'kwargs/reports': 256},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-16',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-17': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-8'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-17', 'kwargs/reports': 289},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-17',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-18': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-9'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-18', 'kwargs/reports': 324},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-18',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-19': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-9'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-19', 'kwargs/reports': 361},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-19',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-20': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-10'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-20', 'kwargs/reports': 400},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-20',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-21': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-10'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-21', 'kwargs/reports': 441},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-21',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-22': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-11'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-22', 'kwargs/reports': 484},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-22',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-23': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-11'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-23', 'kwargs/reports': 529},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-23',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-24': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-12'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-24', 'kwargs/reports': 576},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-24',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-25': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-12'],
    'stage': 'd', 'timeout': null,
    'parameters': {'kwargs/name': '5-25', 'kwargs/reports': 625},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-25',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-26': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-13'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-26', 'kwargs/reports': 676},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-26',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-27': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-13'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-27', 'kwargs/reports': 729},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-27',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-28': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-14'],
    'stage': 'b', 'timeout': null,
    'parameters': {'kwargs/name': '5-28', 'kwargs/reports': 784},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-28',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-29': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-14'],
    'stage': 'g', 'timeout': null,
    'parameters': {'kwargs/name': '5-29', 'kwargs/reports': 841},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-29',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-30': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-15'],
    'stage': 'f', 'timeout': null,
    'parameters': {'kwargs/name': '5-30', 'kwargs/reports': 900},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-30',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  },
  '5-31': {
    'base_task_id': null,
    'queue': null,
    'parents': ['4-15'],
    'stage': 'e', 'timeout': null,
    'parameters': {'kwargs/name': '5-31', 'kwargs/reports': 961},
    'configurations': {},
    'task_overrides': {},
    'executed': null,
    'status': null,
    'clone_task': false,
    'job_type': null,
    'job_started': null,
    'job_ended': null,
    'job_code_section': '5-31',
    'skip_job': false,
    'continue_on_fail': false,
    'cache_executed_step': true,
    'return_artifacts': null,
    'monitor_metrics': null,
    'monitor_artifacts': null,
    'monitor_models': null,
    'job_id': null
  }
};
