/**
 * storage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AwsBucket } from '././awsBucket';


/**
 * AWS S3 storage settings
 */
export interface Aws {
    /**
     * Access key
     */
    key?: string;
    /**
     * Secret key
     */
    secret?: string;
    /**
     * AWS region
     */
    region?: string;
    /**
     * Access token
     */
    token?: string;
    /**
     * If set then use host credentials
     */
    use_credentials_chain?: boolean;
    /**
     * Credential settings per bucket
     */
    buckets?: Array<AwsBucket>;
}
