/**
 * storage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 * Settings per S3 bucket
 */
export interface AwsBucket {
    /**
     * The name of the bucket
     */
    bucket?: string;
    /**
     * The path to match
     */
    subdir?: string;
    /**
     * Host address (for minio servers)
     */
    host?: string;
    /**
     * Access key
     */
    key?: string;
    /**
     * Secret key
     */
    secret?: string;
    /**
     * Access token
     */
    token?: string;
    /**
     * Multipart upload
     */
    multipart?: boolean;
    /**
     * ACL
     */
    acl?: string;
    /**
     * Use SSL connection
     */
    secure?: boolean;
    /**
     * AWS Region
     */
    region?: string;
    /**
     * Verify server certificate
     */
    verify?: boolean;
    /**
     * Use host configured credentials
     */
    use_credentials_chain?: boolean;
}
