/**
 * storage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.12
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Credentials } from './credentials';


export interface Storage {
    /**
     * Entry ID
     */
    id?: string;
    /**
     * Entry name
     */
    name?: string;
    /**
     * Company ID
     */
    company?: string;
    /**
     * Entry creation time
     */
    created?: Date;
    /**
     * Storage URI
     */
    uri?: string;
    credentials?: Credentials;
}
