/**
 * storage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Google } from '././google';
import { Azure } from '././azure';
import { Aws } from '././aws';


export interface StorageGetSettingsResponse {
    /**
     * Settings last update time (UTC)
     */
    last_update?: string;
    aws?: Aws;
    google?: Google;
    azure?: Azure;
}
