/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface DebugImageSampleReposnse {
    /**
     * Scroll ID to pass to the next calls to get_debug_image_sample or next_debug_image_sample
     */
    scroll_id?: string;
    /**
     * Debug image event
     */
    event?: object;
    /**
     * minimal valid iteration for the variant
     */
    min_iteration?: number;
    /**
     * maximal valid iteration for the variant
     */
    max_iteration?: number;
}
