/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsDownloadTaskLogRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * Line format type
     */
    line_type?: EventsDownloadTaskLogRequest.LineTypeEnum;
    /**
     * Line string format. Used if the line type is \'text\'
     */
    line_format?: string;
}
export namespace EventsDownloadTaskLogRequest {
    export type LineTypeEnum = 'json' | 'text';
    export const LineTypeEnum = {
        Json: 'json' as LineTypeEnum,
        Text: 'text' as LineTypeEnum
    }
}
