/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsGetDebugImageIterationsResponse {
    /**
     * Mininal iteration for which a non recycled image exists
     */
    min_iteration?: number;
    /**
     * Maximal iteration for which an image was reported
     */
    max_iteration?: number;
}
