/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ScalarKeyEnum } from '././scalarKeyEnum';


export interface EventsScalarMetricsIterRawRequest {
    /**
     * Task ID
     */
    task: string;
    metric: object;
    key?: ScalarKeyEnum;
    /**
     * The number of data points to return for this call. Optional, the default value   is 5000
     */
    batch_size?: number;
    /**
     * Count the total number of data points. If false, total number of data points is   not counted and null is returned
     */
    count_total?: boolean;
    /**
     * Optional Scroll ID. Use to get more data points following a previous call
     */
    scroll_id?: string;
}
