/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsGetTaskLogRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * The amount of log events to return
     */
    batch_size?: number;
    /**
     * If set then log events are retreived from the latest to the earliest ones (in   timestamp descending order). Otherwise from the earliest to the latest ones (in   timestamp ascending order). The default is True
     */
    navigate_earlier?: boolean;
    /**
     * Epoch time in UTC ms to use as the navigation start
     */
    from_timestamp?: number;
}
