/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 999.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsScalarMetricsIterRawResponse {
    /**
     * Raw data points for each variant
     */
    variants?: object;
    /**
     * Total data points count. If count_total is false, null is returned
     */
    total?: number;
    /**
     * Number of data points returned in this call. If 0 results were returned, no   more results are avilable
     */
    returned?: number;
    /**
     * Scroll ID. Use to get more data points when calling this endpoint again
     */
    scroll_id?: string;
}
