/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsGetTaskEventsRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * \'asc\' (default) or \'desc\'.
     */
    order?: EventsGetTaskEventsRequest.OrderEnum;
    /**
     * Pass this value on next call to get next page
     */
    scroll_id?: string;
    /**
     * Number of events to return each time (default 500)
     */
    batch_size?: number;
    /**
     * Return only events of this type
     */
    event_type?: string;
}
export namespace EventsGetTaskEventsRequest {
    export type OrderEnum = 'asc' | 'desc';
    export const OrderEnum = {
        Asc: 'asc' as OrderEnum,
        Desc: 'desc' as OrderEnum
    }
}
