/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsGetTaskLogRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * Timestamp order in which log events will be returned (defaults to ascending)
     */
    order?: EventsGetTaskLogRequest.OrderEnum;
    /**
     * Where will the log entries be taken from (default to the head of the log)
     */
    from?: EventsGetTaskLogRequest.FromEnum;
    /**
     * 
     */
    scroll_id?: string;
    /**
     * 
     */
    batch_size?: number;
}
export namespace EventsGetTaskLogRequest {
    export type OrderEnum = 'asc' | 'desc';
    export const OrderEnum = {
        Asc: 'asc' as OrderEnum,
        Desc: 'desc' as OrderEnum
    }
    export type FromEnum = 'head' | 'tail';
    export const FromEnum = {
        Head: 'head' as FromEnum,
        Tail: 'tail' as FromEnum
    }
}
