/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsGetDebugImageSampleRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * Metric name
     */
    metric: string;
    /**
     * Metric variant
     */
    variant: string;
    /**
     * The iteration to bring debug image from. If not specified then the latest   reported image is retrieved
     */
    iteration?: number;
    /**
     * If set then scroll state will be refreshed to reflect the latest changes in the   debug images
     */
    refresh?: boolean;
    /**
     * Scroll ID from the previous call to get_debug_image_sample or empty
     */
    scroll_id?: string;
}
