/**
 * events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface EventsGetTaskLogRequest {
    /**
     * Task ID
     */
    task: string;
    /**
     * The amount of log events to return
     */
    batch_size?: number;
    /**
     * If set then log events are retreived from the latest to the earliest ones (in   timestamp descending order, unless order=\'asc\'). Otherwise from the earliest to   the latest ones (in timestamp ascending order, unless order=\'desc\'). The   default is True
     */
    navigate_earlier?: boolean;
    /**
     * Epoch time in UTC ms to use as the navigation start. Optional. If not provided,   reference timestamp is determined by the \'navigate_earlier\' parameter (if true,   reference timestamp is the last timestamp and if false, reference timestamp is   the first timestamp)
     */
    from_timestamp?: number;
    /**
     * If set, changes the order in which log events are returned based on the value   of \'navigate_earlier\'
     */
    order?: EventsGetTaskLogRequest.OrderEnum;
}
export namespace EventsGetTaskLogRequest {
    export type OrderEnum = 'asc' | 'desc';
    export const OrderEnum = {
        Asc: 'asc' as OrderEnum,
        Desc: 'desc' as OrderEnum
    }
}
