/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface AuthGetUsersInfoRequest {
    /**
     * user IDs to retrieve information of
     */
    users?: Array<string>;
    /**
     * user emails to retrieve information of
     */
    emails?: Array<string>;
}
