/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Role } from '././role';


export interface AuthCreateUserRequest {
    /**
     * User name (makes the auth entry more readable)
     */
    name: string;
    /**
     * Associated company ID
     */
    company: string;
    /**
     * Email address uniquely identifying the user
     */
    email: string;
    role?: Role;
    /**
     * Given name
     */
    given_name?: string;
    /**
     * Family name
     */
    family_name?: string;
    /**
     * Avatar URL
     */
    avatar?: string;
}
