/**
 * auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export type Role = 'admin' | 'superuser' | 'user' | 'annotator';

export const Role = {
    Admin: 'admin' as Role,
    Superuser: 'superuser' as Role,
    User: 'user' as Role,
    Annotator: 'annotator' as Role
}
