/**
 * tasks
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {User} from './users/user';
import {Project} from './projects/project';
import { Task } from './tasks/task';
import {IExecution} from '../../core/models/model-data';
import {ItaskOutput} from '@common/core/models/model-data';
import {GetCurrentUserResponseUserObjectCompany} from './users/getCurrentUserResponseUserObjectCompany';


export interface ITask extends Omit<Task, 'user' | 'parent' | 'project' | 'execution' | 'output' | 'company'> {
  user?: User;
  parent?: string | ITask;
  project?: Project;
  execution?: IExecution;
  output: ItaskOutput;
  company: GetCurrentUserResponseUserObjectCompany;
}
