/**
 * models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface MetadataItem {
    /**
     * The key uniquely identifying the metadata item inside the given entity
     */
    key?: string;
    /**
     * The type of the metadata item
     */
    type?: string;
    /**
     * The value stored in the metadata item
     */
    value?: string;
}
