/**
 * models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ModelsSetReadyResponsePublishedTask } from '././modelsSetReadyResponsePublishedTask';


export interface ModelsSetReadyResponse {
    /**
     * Number of models updated (0 or 1)
     */
    updated?: number;
    published_task?: ModelsSetReadyResponsePublishedTask;
}
