/**
 * models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MetadataItem } from '././metadataItem';


export interface ModelsAddOrUpdateMetadataRequest {
    /**
     * ID of the model
     */
    model: string;
    /**
     * Metadata items to add or update
     */
    metadata: Array<MetadataItem>;
}
