/**
 * models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ModelsGetFrameworksRequest {
    /**
     * The list of projects which models will be analyzed. If not passed or empty then   all the company and public models will be analyzed
     */
    projects?: Array<string>;
}
