/**
 * models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ModelsUpdateForTaskRequest {
    /**
     * Task id
     */
    task: string;
    /**
     * URI for the model
     */
    uri?: string;
    /**
     * Model name Unique within the company.
     */
    name?: string;
    /**
     * Model comment
     */
    comment?: string;
    /**
     * User-defined tags
     */
    tags?: Array<string>;
    /**
     * System tags. This field is reserved for system use, please don\'t use it.
     */
    system_tags?: Array<string>;
    /**
     * Override model ID. If provided, this model is updated in the task.
     */
    override_model_id?: string;
    /**
     * Iteration (used to update task statistics)
     */
    iteration?: number;
}
